### ISSUE TITLE
It downloads only posts, I tried it with different reels but not working

### ISSUE THREAD

**Issue by NomanBaigA** [OmaPrakash/Instagram-Downlaoder#1]
- App UI is beautiful
- This app will be amazing if it can download reels, IGTV videos, and stories

**Comment by AndroidWithRossyn** [comment]
you should try:  https://play.google.com/store/apps/details?id=com.banrossyn.post.story.downloader
thank you

**Comment by rohitmaslekar** [comment]
doesn't downlaod reels, only post downlaod, please fix this and also stories doesn't shown.

**Comment by AndroidWithRossyn** [comment]
> doesn't downlaod reels, only post downlaod, please fix this and also stories doesn't shown.
You must use this application, This app works perfectly once you try it. ( https://play.google.com/store/apps/details?id=com.banrossyn.post.story.downloader )

**https://github.com/OmaPrakash/InSaver-Reels-Story-Video**
